import { ProviderRegistry } from "@repo/libraries";

export function createSocialProviderRegistry() {
  return ProviderRegistry.createDefault({
    twitterClientId: process.env.TWITTER_CLIENT_ID,
    twitterClientSecret: process.env.TWITTER_CLIENT_SECRET,
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN,
    telegramDefaultChatId: process.env.TELEGRAM_DEFAULT_CHAT_ID,
    threadsAppId: process.env.THREADS_APP_ID,
    threadsAppSecret: process.env.THREADS_APP_SECRET,
    tiktokClientKey: process.env.TIKTOK_CLIENT_KEY,
    tiktokClientSecret: process.env.TIKTOK_CLIENT_SECRET,
    blueskyPdsUrl: process.env.BLUESKY_PDS_URL,
    dribbbleClientId: process.env.DRIBBBLE_CLIENT_ID,
    dribbbleClientSecret: process.env.DRIBBBLE_CLIENT_SECRET,
    mediumClientId: process.env.MEDIUM_CLIENT_ID,
    mediumClientSecret: process.env.MEDIUM_CLIENT_SECRET,
    youtubeClientId: process.env.YOUTUBE_CLIENT_ID,
    youtubeClientSecret: process.env.YOUTUBE_CLIENT_SECRET,
    instagramAppId: process.env.INSTAGRAM_APP_ID,
    instagramAppSecret: process.env.INSTAGRAM_APP_SECRET,
    discordClientId: process.env.DISCORD_CLIENT_ID,
    discordClientSecret: process.env.DISCORD_CLIENT_SECRET,
    redditClientId: process.env.REDDIT_CLIENT_ID,
    redditClientSecret: process.env.REDDIT_CLIENT_SECRET,
    redditUserAgent: process.env.REDDIT_USER_AGENT,
    linkedinClientId: process.env.LINKEDIN_CLIENT_ID,
    linkedinClientSecret: process.env.LINKEDIN_CLIENT_SECRET,
    pinterestAppId: process.env.PINTEREST_APP_ID,
    pinterestAppSecret: process.env.PINTEREST_APP_SECRET,
    facebookAppId: process.env.FACEBOOK_APP_ID,
    facebookAppSecret: process.env.FACEBOOK_APP_SECRET,
    googleBusinessClientId: process.env.GOOGLE_BUSINESS_CLIENT_ID,
    googleBusinessClientSecret: process.env.GOOGLE_BUSINESS_CLIENT_SECRET,
    slackClientId: process.env.SLACK_CLIENT_ID,
    slackClientSecret: process.env.SLACK_CLIENT_SECRET,
    whatsappAccessToken: process.env.WHATSAPP_ACCESS_TOKEN,
    mastodonInstanceUrl: process.env.MASTODON_INSTANCE_URL,
    whopApiKey: process.env.WHOP_API_KEY,
    twitchClientId: process.env.TWITCH_CLIENT_ID,
    twitchClientSecret: process.env.TWITCH_CLIENT_SECRET,
    skoolApiKey: process.env.SKOOL_API_KEY,
    kickClientId: process.env.KICK_CLIENT_ID,
    warpcastApiKey: process.env.WARPCAST_API_KEY,
    vkClientId: process.env.VK_CLIENT_ID,
    vkClientSecret: process.env.VK_CLIENT_SECRET,
    lemmyInstanceUrl: process.env.LEMMY_INSTANCE_URL,
    meweClientId: process.env.MEWE_CLIENT_ID,
    nostrRelayUrl: process.env.NOSTR_RELAY_URL,
    listmonkApiUrl: process.env.LISTMONK_API_URL,
    wordpressClientId: process.env.WORDPRESS_CLIENT_ID,
    hashnodeApiKey: process.env.HASHNODE_API_KEY,
    githubClientId: process.env.GITHUB_CLIENT_ID,
    githubClientSecret: process.env.GITHUB_CLIENT_SECRET,
    gitlabClientId: process.env.GITLAB_CLIENT_ID,
    producthuntClientId: process.env.PRODUCTHUNT_CLIENT_ID,
    producthuntClientSecret: process.env.PRODUCTHUNT_CLIENT_SECRET,
    hackernewsApiKey: process.env.HACKERNEWS_API_KEY,
    substackApiKey: process.env.SUBSTACK_API_KEY,
    beehiivApiKey: process.env.BEEHIIV_API_KEY,
    ghostAdminApiKey: process.env.GHOST_ADMIN_API_KEY,
    notionIntegrationSecret: process.env.NOTION_INTEGRATION_SECRET,
    patreonClientId: process.env.PATREON_CLIENT_ID,
    spotifyClientId: process.env.SPOTIFY_CLIENT_ID,
    behanceClientId: process.env.BEHANCE_CLIENT_ID,
    tumblrClientId: process.env.TUMBLR_CLIENT_ID,
  });
}

export function providerIdForPlatform(platform: string) {
  return platform === "x" ? "twitter" : platform;
}
